-- ─── TABLE: HNEWMaster ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."HNEWMaster" (
    DocID serial NOT NULL,
    Title character varying(500),
    Content text,
    WriterID character varying(50),
    WriterNm character varying(50),
    OrgCd character varying(8000),
    OrgNm text,
    RegYmd character varying(8),
    EndYmd character varying(8),
    ImpYn character varying(1),
    PopYn character varying(1),
    Hit integer,
    GroupCd character varying(4),
    AuthCd character varying(20),
    Acnt integer,
    Ocnt integer,
    att1 character varying(100),
    att2 character varying(100),
    att3 character varying(100),
    att4 character varying(100),
    att5 character varying(100),
    IsGroupReg smallint DEFAULT 0,
    OrgcdU text DEFAULT '',
    messangerYN character(1),
    IsPermanent character(1),
    PopupStartYmd character(8),
    PopupEndYmd character(8),
    IsPopupPermanent character(1)
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
