-- ─── TABLE: TCMCompanyInfo ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."TCMCompanyInfo" (
    ID serial NOT NULL,
    RegUserNo integer,
    RegUserName character varying(50),
    RegDate timestamp without time zone,
    Name character varying(100),
    Num character varying(50),
    Type1Code integer,
    Type1Desc character varying(100),
    Type2Code integer,
    Type2Desc character varying(100),
    Type3Code integer,
    Type3Desc character varying(100),
    Type4Code character(1),
    Type4Desc character varying(100),
    ConnectDate date,
    CEOName character varying(100),
    Site character varying(100),
    TelNo character varying(50),
    FaxNo character varying(50),
    Addr character varying(100),
    Bank character varying(100),
    Trust character varying(100),
    Sales character varying(100),
    Scale character varying(100),
    Staff character varying(1000),
    Etc text,
    RegionCode integer,
    RegionName character varying(100),
    Ranking character varying(50),
    CompanyType character(1),
    FirstUserId character varying(1000),
    FirstUserName character varying(1000),
    SecondUserId character varying(1000),
    SecondUserName character varying(1000),
    SalesDate date,
    SalesAmount numeric(18,0),
    ProductCode integer,
    ProductName character varying(100),
    StateCode integer,
    StateDesc character varying(100),
    Path character varying(1000),
    NextDate character varying(10),
    NextTime character varying(5),
    Comment text,
    RankingCode integer,
    RankingDesc character varying(10)
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
