-- ─── TABLE: _TDAEmpIn ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."_TDAEmpIn" (
    CompanySeq integer NOT NULL,
    EmpSeq integer NOT NULL,
    EmpID character varying(20),
    UMEmpType integer,
    EntDate character(8),
    RetireDate character(8),
    IsDisabled character(1),
    IsForeigner character(1),
    SMBirthType integer,
    BirthDate character(8),
    UMNationSeq integer,
    SMSexSeq integer,
    IsMarriage character(1),
    MarriageDate character(8),
    UMReligionSeq integer,
    Hobby character varying(200),
    Speciality character varying(200),
    Phone character varying(20),
    Cellphone character varying(20),
    Extension character varying(20),
    Email character varying(50),
    Remark text,
    UMEmployType integer,
    WishTask1 character varying(200),
    WishTask2 character varying(200),
    Recommender character varying(200),
    RcmmndrCom character varying(200),
    RcmmndrRank character varying(200),
    PrevEmpSeq integer,
    LastUserSeq integer,
    LastDateTime timestamp without time zone,
    Height numeric(19,5),
    Weight numeric(19,5),
    SMBloodType integer,
    UMHandiType integer,
    UMHandiGrd integer,
    HandiAppdate character(8),
    IsVeteranEmp character(1),
    VeteranNo character varying(50),
    UMRelSeq integer,
    IsJobEmp character(1),
    EyeLt numeric(19,5),
    EyeRt numeric(19,5),
    People integer,
    UMHouseSort integer,
    IsDivision character(1),
    IsDelete character(1),
    HandiEndDate character(8),
    PRIMARY KEY (CompanySeq, EmpSeq)
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
