-- ─── TABLE: DMake_Boards_Fields ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."DMake_Boards_Fields" (
    FieldNo serial NOT NULL,
    BoardNo integer,
    ControlNo integer,
    Label_KO character varying(100),
    Label_EN character varying(100),
    Label_JP character varying(100),
    Label_CH character varying(100),
    Label_VN character varying(100),
    FieldUpNo integer,
    SortNo integer,
    ListNo integer,
    ListYN character varying(1),
    SearchYN character varying(1),
    FieldName character varying(50),
    FieldDataType character varying(50),
    FieldType character varying(5),
    FieldReadOnly character varying(1),
    FieldRequire character varying(1),
    Width character varying(10),
    Height character varying(10),
    ClassNo integer,
    PopupYn character varying(1),
    PopupLink character varying(1000),
    ImagePath character varying(500),
    Enabled boolean,
    LabelTextAlign character varying(20),
    LabelBackColor character varying(20),
    LabelFontWeight character varying(20),
    ChartYN character varying(1)
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
