-- ─── TABLE: DMake_Contents ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."DMake_Contents" (
    ContentNo bigserial NOT NULL,
    BoardNo integer,
    Title character varying(200),
    TitleEffect integer,
    Content text,
    IsFile boolean,
    FileCount integer,
    ReplyCount integer,
    RecommendedCount integer,
    ViewedCount integer,
    IsDeleted boolean,
    StartDate character varying(10),
    EndDate character varying(10),
    IsHead boolean,
    IsApproval character varying(1),
    ApprovalUserNo integer,
    ApprovalDate timestamp without time zone,
    IsAnomymous boolean,
    ParentNo integer,
    RegUserNo integer,
    RegUserName character varying(100),
    RegDate timestamp without time zone,
    ModUserNo integer,
    ModUserName character varying(100),
    ModDate timestamp without time zone,
    DMakeField01 character varying(100),
    DMakeField02 character varying(100),
    DMakeField03 character varying(100),
    DMakeField04 character varying(100),
    DMakeField05 character varying(100),
    DMakeField06 character varying(100),
    DMakeField07 character varying(100),
    DMakeField08 character varying(100),
    DMakeField09 character varying(100),
    DMakeField10 character varying(100)
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
