-- ─── TABLE: EAPPForm ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."EAPPForm" (
    ID serial NOT NULL,
    SeqNo integer,
    Name character varying(100),
    Content text,
    BoardID character varying(50),
    PathID integer,
    FixedPath character(1),
    StorePeriod integer,
    EACode character varying(50),
    FormType character varying(4),
    RegDate timestamp without time zone,
    RegID character varying(50),
    ModDate timestamp without time zone,
    ModID character varying(50),
    Code character varying(20),
    Width integer,
    Height integer,
    IsOpenWindow character(1),
    IsDelete character(1),
    IsErp character(1),
    CategoryID integer,
    ErpType character varying(10),
    IsFixedForm character(1),
    IsUsing character(1),
    DepartID character(4),
    DraftLine character(1),
    AgreeLine character(1),
    AssistLine character(1),
    ProposalLine character(1),
    ExecuteLine character(1),
    AuditLine character(1),
    ReceiveLine character(1),
    ReferenceLine character(1),
    DraftCount integer,
    AgreeCount integer,
    AssistCount integer,
    ProposalCount integer,
    ExecuteCount integer,
    AuditCount integer,
    ReceiveCount integer,
    ReferenceCount integer,
    PrintType character(1),
    TopMargin character varying(10),
    BottomMargin character varying(10),
    LeftMargin character varying(10),
    RightMargin character varying(10),
    OperationType integer,
    RequireManager character(1),
    Description character varying(500),
    Standard character varying(200),
    ModApproval character(1),
    ReApproval character(1),
    PassageLine character(1),
    PassageCount integer,
    IsClose character(1),
    ERPFixedPath character(1),
    EDMSSet character(1),
    IsErpStartGW character varying(1),
    SerialLang character varying(1),
    IsMod character(1),
    EDMSFolderID character varying(100),
    EDMSFolderFix character(1),
    EDMSAuth character varying(2000),
    EDMSAuthFix character(1),
    EDMSAuthDefault character(1),
    DocSerial character varying(100),
    IsHotNews character(1),
    YesanLine character(1),
    YesanCount integer,
    GamsaLine character(1),
    GamsaCount integer,
    PopUpUrl character varying(2000),
    UseTemp character(1),
    UseMod character(1),
    UseDel character(1),
    PreFinalLine character(1),
    PreFinalCount integer,
    FinalLine character(1),
    FinalCount integer,
    IsShare character(1),
    ProAgreeLine character(1),
    ProAgreeCount integer,
    ExeAgreeLine character(1),
    ExeAgreeCount integer,
    noDecision character(1),
    EDMSAuthorityLevel integer NOT NULL,
    LinkForm character(1) NOT NULL,
    RotationLine character(1) NOT NULL,
    RotationCount integer NOT NULL
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
