-- ─── TABLE: EAPPUserEnv ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."EAPPUserEnv" (
    UserID character varying(50) NOT NULL PRIMARY KEY,
    ShortenName character varying(50),
    Password character varying(100),
    SignPath character varying(255),
    Absence character(1),
    AbsenceProg character(1),
    RepresenterID character varying(50),
    NoteRcvState character varying(20),
    NoteRcvArrive character varying(20),
    NoteRcvAll character varying(20),
    NoteForMessanger character(1),
    NoteForSMS character(1),
    NoteForEmail character(1),
    DefaultPrintStyle character(1),
    FileNameFormat character varying(50),
    AutoOpenLock character(1),
    ApprovalPosition character(1),
    EAPPRule character(1),
    DefaultPathID integer,
    CompanyColor character varying(50),
    PreviewID integer,
    StoreToDelete character(1),
    ReferenceAutoConfirm character(1),
    OperationAddress character varying(200),
    OperationTel character varying(50),
    OperationFax character varying(50),
    UnloadMsg integer,
    ReceiveAutoConfirm character(1),
    SummaryPosition character(1),
    NextSeleter character varying(50),
    ProgressView character(1),
    TotalApproval character(1) NOT NULL,
    ShowCount character varying(20),
    ApprovalContinue character(1) NOT NULL
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
