-- ─── TABLE: EDMSDocument ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."EDMSDocument" (
    ID serial NOT NULL,
    Title character varying(500),
    Content text,
    WriterID character varying(50),
    PositionID character varying(4),
    DepartID character varying(4),
    GradeID character varying(4),
    GroupCode character varying(4),
    WOrder integer,
    WLevel integer,
    WGroup integer,
    IsNotice character(1),
    LCategory integer,
    SCategory integer,
    AuthorityLevel integer,
    IsSecret character(1),
    Hit integer,
    RegDate timestamp without time zone,
    Modifier character varying(50),
    ModDate timestamp without time zone,
    ValDate timestamp without time zone,
    IsDelete character(1),
    Description character varying(500),
    State character(1),
    Serial character varying(100),
    StorePeriod integer,
    HistoryID integer,
    Summary text,
    Version character varying(50),
    KeyWord character varying(200),
    ContentText text,
    timestamp timestamp,
    EADocFlag integer,
    CheckoutId character varying(50),
    Docstate character(1),
    VersionState character varying(1),
    DocLevel character varying(10)
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
