-- ─── TABLE: Mail_Mails ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."Mail_Mails" (
    MailNo bigserial NOT NULL,
    CMSendNum bigint NOT NULL,
    UserNo integer NOT NULL,
    BoxNo bigint NOT NULL,
    FromName character varying(400),
    FromAddr character varying(400),
    To text NOT NULL,
    Cc text NOT NULL,
    Bcc text NOT NULL,
    ToDomain character varying(100) NOT NULL,
    AccNo bigint NOT NULL,
    Title character varying(2000),
    Content text NOT NULL,
    IsSent boolean NOT NULL,
    ReplyDate timestamp without time zone,
    ForwardDate timestamp without time zone,
    IsDelete boolean NOT NULL,
    TagNo bigint NOT NULL,
    TextMode integer NOT NULL,
    Size integer NOT NULL,
    FileCount integer NOT NULL,
    RegDate timestamp without time zone NOT NULL,
    ReadDate timestamp without time zone,
    EmlFileName character varying(100) NOT NULL,
    IsOneByOne boolean NOT NULL,
    IsImportant boolean NOT NULL,
    RecipientsCount integer NOT NULL,
    ReadCount integer NOT NULL,
    Priority character(1) NOT NULL,
    ReserveDate timestamp without time zone,
    IsFile boolean NOT NULL,
    IsCalendar boolean NOT NULL,
    ConversationNo bigint NOT NULL,
    RegUserNo integer NOT NULL,
    DeleteDate timestamp without time zone,
    PRIMARY KEY (MailNo, UserNo, BoxNo, AccNo, IsDelete)
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
