-- ─── TABLE: Organization_Users ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."Organization_Users" (
    UserNo serial NOT NULL,
    ModUserNo integer NOT NULL,
    ModDate timestamp without time zone NOT NULL,
    UserID character varying(100) NOT NULL,
    Password character varying(200),
    PasswordChangeDate timestamp without time zone NOT NULL,
    Name character varying(100) NOT NULL,
    Name_EN character varying(100) NOT NULL,
    MailAddress character varying(200) NOT NULL,
    Sex integer NOT NULL,
    CellPhone character varying(100) NOT NULL,
    CompanyPhone character varying(100) NOT NULL,
    ExtensionNumber character varying(20) NOT NULL,
    EntranceDate timestamp without time zone NOT NULL,
    BirthDate timestamp without time zone NOT NULL,
    UserPhoto boolean NOT NULL,
    Photo character varying(500) NOT NULL,
    TimeZone character varying(200) NOT NULL,
    Enabled boolean NOT NULL,
    IsVirtual boolean NOT NULL,
    Name_CH character varying(200) NOT NULL,
    Name_JP character varying(200) NOT NULL,
    Name_VN character varying(200) NOT NULL,
    WorkPlaceType character varying(20),
    GroupId integer,
    SkinName character varying(50),
    FaxNumber character varying(100),
    FailedLoginCount integer NOT NULL,
    BirthDateType integer NOT NULL
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
