-- ─── TABLE: TCMBusinessInfo ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."TCMBusinessInfo" (
    ID serial NOT NULL,
    CompanyID integer,
    RegUserNo integer,
    RegUserID character varying(50),
    RegUserName character varying(100),
    BsnsDate timestamp without time zone,
    Type1Code integer,
    Type1Desc character varying(50),
    Type2Code integer,
    Type2Desc character varying(50),
    ClientStaffID integer,
    ClientStaffName character varying(100),
    Money character varying(50),
    Subject character varying(200),
    Content text,
    NDate date,
    SalesDate date,
    SalesComment character varying(500),
    RegDate timestamp without time zone,
    NextDate timestamp without time zone,
    NextAction character varying(200),
    NextActionYn character(1),
    ApprovalID character varying(1000),
    MailSeq character varying(1000),
    AuthUser character varying(4000),
    AuthUserName character varying(4000),
    ImportantNote text
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
