-- ─── TABLE: _TPRWkYyEmpDays ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."_TPRWkYyEmpDays" (
    CompanySeq integer NOT NULL,
    YY character(4) NOT NULL,
    EmpSeq integer NOT NULL,
    ProcMM character(2),
    BasePayYM character(6),
    PayYM character(6),
    PileDays numeric(19,5),
    ExProbOccurDays numeric(19,5),
    ExProbUseDays numeric(19,5),
    OccurDays numeric(19,5),
    RestDays numeric(19,5),
    AbsDays numeric(19,5),
    OccurFrDate character(8),
    OccurToDate character(8),
    UseFrDate character(8),
    UseEndDate character(8),
    UseToDate character(8),
    BasePileDays numeric(19,5),
    AddPileDays numeric(19,5),
    PbSeq integer,
    IsEnd character(1),
    GnerAmtYyMm character(6),
    LastUserSeq integer,
    LastDateTime timestamp without time zone,
    DutyDays numeric(19,5),
    AddDays numeric(19,5),
    PileTime numeric(19,5),
    OccurTime numeric(19,5),
    RestTime numeric(19,5),
    AbsTime numeric(19,5),
    PRIMARY KEY (CompanySeq, YY, EmpSeq)
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
