-- TODO: constraint conversion is not implemented yet: dbo.Board_AuthoGroup.PK__Board_Au__E6B77A6E34D628CE
-- RAW:
-- Source table: [dbo].[Board_AuthoGroup]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
