-- TODO: constraint conversion is not implemented yet: dbo.Center_CompanyInformation.PK_Center_CompanyInformation
-- RAW:
-- Source table: [dbo].[Center_CompanyInformation]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
