-- TODO: constraint conversion is not implemented yet: dbo.Center_MobileSessions.PK_Center_MobileSessions
-- RAW:
-- Source table: [dbo].[Center_MobileSessions]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
