-- TODO: constraint conversion is not implemented yet: dbo.CrewChat_FavoriteChatRoom.PK_CrewChat_FavoriteChatRoom
-- RAW:
-- Source table: [dbo].[CrewChat_FavoriteChatRoom]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
