-- TODO: constraint conversion is not implemented yet: dbo.DDay_GroupInfoOfSharedDays.PK_DDay_GroupInfoOfSharedDays
-- RAW:
-- Source table: [dbo].[DDay_GroupInfoOfSharedDays]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
