-- TODO: constraint conversion is not implemented yet: dbo.DMake_Field_Copy_History.PK_DMake_Field_Copy_History
-- RAW:
-- Source table: [dbo].[DMake_Field_Copy_History]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
