-- TODO: constraint conversion is not implemented yet: dbo.EAPPLinkConnection.PK__EAPPLink__3213E83F21EF083A
-- RAW:
-- Source table: [dbo].[EAPPLinkConnection]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
