-- TODO: constraint conversion is not implemented yet: dbo.Notice_UserByGroup.PK__Notice_U__AE84E16749D145B4
-- RAW:
-- Source table: [dbo].[Notice_UserByGroup]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
