-- TODO: constraint conversion is not implemented yet: dbo.SourceControl_CompanyHistory.PK_SourceControl_CompanyHistory
-- RAW:
-- Source table: [dbo].[SourceControl_CompanyHistory]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
