-- TODO: constraint conversion is not implemented yet: dbo.SourceControl_DatabaseHistory.PK_SourceControl_DatabaseHistory
-- RAW:
-- Source table: [dbo].[SourceControl_DatabaseHistory]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
