-- TODO: constraint conversion is not implemented yet: dbo.WebService_GCMRegistration.PK_WebService_GCMRegistration
-- RAW:
-- Source table: [dbo].[WebService_GCMRegistration]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
