-- TODO: constraint conversion is not implemented yet: dbo.WorkingTime_BoxUses.PK__WorkingT__3214D4A8199CE6B7
-- RAW:
-- Source table: [dbo].[WorkingTime_BoxUses]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
