-- TODO: constraint conversion is not implemented yet: dbo.WorkingTime_DisplayPaths.PK_WorkingTime_DisplayPaths
-- RAW:
-- Source table: [dbo].[WorkingTime_DisplayPaths]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
