-- TODO: constraint conversion is not implemented yet: dbo.WorkingTime_Settings.PK_WorkingTimeSettings
-- RAW:
-- Source table: [dbo].[WorkingTime_Settings]
-- Constraint type: PRIMARY_KEY_CONSTRAINT
