-- ─── TABLE: BIZ_MSG ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."BIZ_MSG" (
    CMID character varying(32) NOT NULL PRIMARY KEY,
    UMID character varying(32),
    MSG_TYPE integer DEFAULT 0,
    STATUS integer DEFAULT 0,
    CALL_STATUS character varying(4),
    REQUEST_TIME timestamp without time zone NOT NULL,
    SEND_TIME timestamp without time zone NOT NULL,
    REPORT_TIME timestamp without time zone,
    DEST_PHONE character varying(16),
    SEND_PHONE character varying(16),
    DEST_NAME character varying(32),
    SEND_NAME character varying(32),
    SUBJECT character varying(64),
    MSG_BODY character varying(2000),
    NATION_CODE character varying(5),
    SENDER_KEY character varying(40),
    TEMPLATE_CODE character varying(64),
    RESPONSE_METHOD character varying(8),
    TIMEOUT integer,
    RE_TYPE character varying(3) DEFAULT 'N',
    RE_BODY character varying(2000),
    RE_PART character varying(1),
    COVER_FLAG integer DEFAULT 0,
    SMS_FLAG integer DEFAULT 0,
    REPLY_FLAG integer DEFAULT 0,
    RETRY_CNT integer,
    ATTACHED_FILE character varying(1000),
    VXML_FILE character varying(64),
    USE_PAGE integer DEFAULT 0,
    USE_TIME integer DEFAULT 0,
    SN_RESULT integer DEFAULT 0,
    TEL_INFO character varying(10) DEFAULT '-',
    CINFO character varying(32),
    USER_KEY character varying(30),
    AD_FLAG character varying(1),
    RCS_REFKEY character varying(32)
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
