-- ─── TABLE: WorkingTime_Times ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."WorkingTime_Times" (
    WorkingNo serial NOT NULL,
    RegUserNo integer NOT NULL,
    RegDate timestamp without time zone NOT NULL,
    UserNo integer NOT NULL,
    WorkingDay integer NOT NULL,
    TimeType integer NOT NULL,
    CheckTime character(6) NOT NULL,
    Provider integer NOT NULL,
    Latitude double precision NOT NULL,
    Longitude double precision NOT NULL,
    Remark character varying(500),
    IpServer character varying(250),
    TimeCheckLong double precision,
    TimeOffset double precision DEFAULT 9,
    Distance character varying(250),
    LatCompany double precision,
    LngCompany double precision,
    BeaconInfo character varying(500),
    NameCompany character varying(500),
    PostId character varying(50),
    PostName character varying(500),
    DeptId character varying(50),
    DeptName character varying(500),
    LocationNo integer,
    GroupId integer,
    LunchStart character(4),
    LunchEnd character(4),
    StarWorking character(4),
    EndWorking character(4),
    IsAddLunch boolean,
    BIn1 character(4),
    BOut1 character(4),
    BIn2 character(4),
    BOut2 character(4),
    IsB1 boolean,
    IsB2 boolean,
    TimeWorking integer,
    WorkingDayC integer,
    CheckTimeC integer,
    CheckTimeFull timestamp without time zone,
    TimeWorking2 integer,
    address character varying(600),
    status integer,
    Dateupdate timestamp without time zone,
    DateDelete timestamp without time zone,
    CheckTimeFullO timestamp without time zone,
    Userdeleted integer,
    bno integer,
    bname character varying(500),
    TimeWorkingf integer,
    TimeWorkingf2 integer
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
