-- ─── TABLE: Board_Contents ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."Board_Contents" (
    ContentNo bigserial NOT NULL,
    BoardNo integer NOT NULL,
    ModUserNo integer NOT NULL,
    ModUserName character varying(100) NOT NULL,
    ModPositionNo integer NOT NULL,
    ModPositionName character varying(100) NOT NULL,
    ModDepartNo integer NOT NULL,
    ModDepartName character varying(100) NOT NULL,
    RegDate timestamp without time zone NOT NULL,
    ModDate timestamp without time zone NOT NULL,
    Title character varying(200) NOT NULL,
    TitleEffect integer NOT NULL,
    GroupNo bigint NOT NULL,
    Depth integer NOT NULL,
    OrderNo integer NOT NULL,
    HeadNo integer NOT NULL,
    IsNotice boolean NOT NULL,
    Content text NOT NULL,
    IsFile boolean NOT NULL,
    FileCount integer NOT NULL,
    ReplyCount integer NOT NULL,
    RecommendedCount integer NOT NULL,
    ViewedCount integer NOT NULL,
    StartDate timestamp without time zone,
    EndDate timestamp without time zone,
    Enabled boolean NOT NULL,
    RegUserNo integer,
    RegPositionNo integer,
    RegDepartNo integer,
    ViewMode integer,
    IsAlarm boolean,
    RootId bigint,
    LevelRand character varying(500),
    IsShareAll boolean,
    Type character varying(1000),
    ErrorType character varying(1000),
    PersonType character varying(1000),
    VisitDate timestamp without time zone,
    VisitCompleteDate timestamp without time zone,
    DateView timestamp without time zone,
    DesignNo character varying(1000),
    ConstructionName character varying(1000),
    ApplyTo character varying(1000),
    Important boolean,
    MailRecipientNo text,
    MailRecipientName text,
    Private boolean,
    BusinessDate timestamp without time zone,
    Purpose character varying(1000),
    Note character varying(1000),
    Other text,
    Inspector character varying(1000),
    Generation character varying(1000),
    BadNo character varying(1000),
    Standard character varying(1000),
    IsRecommendPublic boolean,
    EappNo integer,
    PRIMARY KEY (ContentNo, GroupNo, Depth)
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
