-- ─── TABLE: EAPPDocument ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."EAPPDocument" (
    ID serial NOT NULL,
    Title character varying(200),
    Content text,
    WriterID character varying(50),
    PositionID character varying(4),
    DepartID character varying(4),
    GradeID character varying(4),
    WOrder integer,
    WLevel integer,
    WGroup integer,
    IsNotice character(1),
    LCategory character varying(50),
    SCategory character varying(50),
    AuthorityLevel integer,
    IsSecret character(1),
    Hit integer,
    RegDate timestamp without time zone,
    Modifier character varying(50),
    ModDate timestamp without time zone,
    ValDate timestamp without time zone,
    IsDelete character(1),
    Description character varying(100),
    PathID integer,
    ProgID integer,
    State integer,
    FormID integer,
    Serial character varying(100),
    OperationDate character varying(50),
    StorePeriod integer,
    ContentID integer,
    TotalStoredBoxID integer,
    HistoryID integer,
    ErpKey text,
    DocSign character varying(200),
    AgreeOrder integer,
    Duty character(1),
    Drafter character(1),
    RootID integer,
    Summary text,
    ContentText text,
    OpinionText text,
    FileNameText text,
    timestamp timestamp,
    GroupCode character(4),
    IsDraftDel character(1),
    OperationType integer,
    EDMSID integer,
    EDMSState integer,
    IsClose character(1),
    AgreeDocId integer,
    AgreeManagerID character varying(100),
    BSCODE character varying(20),
    DeptName1 character varying(100),
    DeptName2 character varying(100),
    DeptName3 character varying(100),
    DeptName4 character varying(100),
    IsAutoAfter character(1)
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
