-- ─── TABLE: ScheduleContents ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."ScheduleContents" (
    ScheduleNo serial NOT NULL,
    RegUserNo integer NOT NULL,
    RegDate timestamp without time zone NOT NULL,
    ModUserNo integer NOT NULL,
    ModDate timestamp without time zone NOT NULL,
    Title character varying(100) NOT NULL,
    CalendarNo integer NOT NULL,
    DivisionNo integer NOT NULL,
    Content text,
    IsLunar character(1) NOT NULL DEFAULT '0',
    IsHoliday integer NOT NULL DEFAULT 0,
    IsFiveWeek character(1) NOT NULL DEFAULT '0',
    IsLastDay character(1) NOT NULL DEFAULT '0',
    RepeatType integer NOT NULL,
    RepeatCount integer NOT NULL,
    RepeatMonth integer NOT NULL,
    RepeatWeek integer NOT NULL,
    RepeatDay integer NOT NULL,
    RepeatDOWs integer NOT NULL,
    StartDate date NOT NULL,
    EndDate date NOT NULL,
    StartTime time without time zone NOT NULL,
    EndTime time without time zone NOT NULL,
    IsAllDay boolean NOT NULL,
    IsNotiNote boolean NOT NULL,
    IsNotiMail boolean NOT NULL,
    IsNotiSMS boolean NOT NULL,
    IsNotiPopup boolean NOT NULL,
    NotiTimeType integer NOT NULL,
    Place character varying(200) NOT NULL DEFAULT '',
    Latitude double precision NOT NULL DEFAULT 0,
    Longitude double precision NOT NULL DEFAULT 0,
    IsCompleted boolean,
    Idea text,
    CycleNo integer,
    OldScheduleNo integer,
    ScheduleNoOldverson integer,
    writer character varying(20)
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
