-- TODO: constraint conversion not implemented for: dbo.Board_CommentSetting.DF__Board_Com__RegDa__6C753A85
-- -- Source table: [dbo].[Board_CommentSetting]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
