-- TODO: constraint conversion not implemented for: dbo.Board_MultiBoardWidget.DF__Board_Mul__IsDel__46B9A5F1
-- -- Source table: [dbo].[Board_MultiBoardWidget]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('FALSE')
