-- TODO: constraint conversion not implemented for: dbo.Board_NewBoardWidget.DF__Board_New__RegDa__7CF5BB11
-- -- Source table: [dbo].[Board_NewBoardWidget]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
