-- TODO: constraint conversion not implemented for: dbo.Board_NewBoardWidget.DF__Board_New__IsDel__7FD227BC
-- -- Source table: [dbo].[Board_NewBoardWidget]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('FALSE')
