-- TODO: constraint conversion not implemented for: dbo.Board_UserByGroup.DF__Board_Use__DTS_U__31F9BC23
-- -- Source table: [dbo].[Board_UserByGroup]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
