-- TODO: constraint conversion not implemented for: dbo.Center_NotificationService_AlarmDetail.DF_Center_NotificationService_AlarmDetail_RegDate
-- -- Source table: [dbo].[Center_NotificationService_AlarmDetail]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
