-- TODO: constraint conversion not implemented for: dbo.Commute_Schedule.DF__Commute_S__UserN__22522849
-- -- Source table: [dbo].[Commute_Schedule]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
