-- TODO: constraint conversion not implemented for: dbo.Commute_Schedule.DF__Commute_S__EndTi__215E0410
-- -- Source table: [dbo].[Commute_Schedule]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (N'')
