-- TODO: constraint conversion not implemented for: dbo.Commute_Schedule.DF__Commute_S__AppUs__243A70BB
-- -- Source table: [dbo].[Commute_Schedule]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
