-- TODO: constraint conversion not implemented for: dbo.Commute_TimeShift.DF__Commute_T__SortN__17D499D6
-- -- Source table: [dbo].[Commute_TimeShift]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
