-- TODO: constraint conversion not implemented for: dbo.Contact_ShareGroup.DF__Contact_S__ModDa__6923CC8E
-- -- Source table: [dbo].[Contact_ShareGroup]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
