-- TODO: constraint conversion not implemented for: dbo.Contact_ShareGroup.DF__Contact_S__IsDel__6A17F0C7
-- -- Source table: [dbo].[Contact_ShareGroup]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('FALSE')
