-- TODO: constraint conversion not implemented for: dbo.Contact_ShareGroup.DF__Contact_S__RegDa__682FA855
-- -- Source table: [dbo].[Contact_ShareGroup]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
