-- TODO: constraint conversion not implemented for: dbo.Contact_PublicGroupUser.DF__Contact_P__ModDa__70C4EE56
-- -- Source table: [dbo].[Contact_PublicGroupUser]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
