-- TODO: constraint conversion not implemented for: dbo.Contact_ShareGroupUser.DF__Contact_S__IsDel__7589A373
-- -- Source table: [dbo].[Contact_ShareGroupUser]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('FALSE')
