-- TODO: constraint conversion not implemented for: dbo.ContactsCompanyHistory.PK_ContactsCompanyHistory
-- -- Source table: [dbo].[ContactsCompanyHistory]
-- -- Constraint type: PRIMARY_KEY_CONSTRAINT
--
