-- TODO: constraint conversion not implemented for: dbo.ContactsGroupOutlook.DF_ContactsGroupOutlook_OutlookFolderEntryID
-- -- Source table: [dbo].[ContactsGroupOutlook]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('')
