-- TODO: constraint conversion not implemented for: dbo.CrewChat_Rooms.DF_CrewChat_Rooms_LastedMsgAttachName
-- -- Source table: [dbo].[CrewChat_Rooms]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('')
