-- TODO: constraint conversion not implemented for: dbo.CrewChat_UserProfiles.DF_CrewChat_UserProfiles_StateName
-- -- Source table: [dbo].[CrewChat_UserProfiles]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('')
