-- TODO: constraint conversion not implemented for: dbo.DMake_Auth_Depart.DF_DMake_Auth_Depart_IsDelete
-- -- Source table: [dbo].[DMake_Auth_Depart]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
