-- TODO: constraint conversion not implemented for: dbo.DMake_Boards_Fields.DF_DMake_Boards_Fields_ListYN
-- -- Source table: [dbo].[DMake_Boards_Fields]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (N'N')
