-- TODO: constraint conversion not implemented for: dbo.DMake_Field_Copy_History.DF_DMake_Field_Copy_History_BoardNo
-- -- Source table: [dbo].[DMake_Field_Copy_History]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
