-- TODO: constraint conversion not implemented for: dbo.DMake_RecommendLog.DF_DMake_RecommendLog_UserNo
-- -- Source table: [dbo].[DMake_RecommendLog]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
