-- TODO: constraint conversion not implemented for: dbo.DMake_RecommendLog.DF_DMake_RecommendLog_RecomendDate
-- -- Source table: [dbo].[DMake_RecommendLog]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
