-- TODO: constraint conversion not implemented for: dbo.Drive_PemissionCommonFolders.PK_Drive_Drive_PemissionCommonFolders
-- -- Source table: [dbo].[Drive_PemissionCommonFolders]
-- -- Constraint type: PRIMARY_KEY_CONSTRAINT
--
