-- TODO: constraint conversion not implemented for: dbo.Note_Comments.DF_Note_Comments_ParentID
-- -- Source table: [dbo].[Note_Comments]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (CONVERT([uniqueidentifier],CONVERT([binary],(0),(0)),(0)))
