-- TODO: constraint conversion not implemented for: dbo.NoticeSyn_AuthoGroup.DF__NoticeSyn__DTS_I__3C1B5096
-- -- Source table: [dbo].[NoticeSyn_AuthoGroup]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
