-- TODO: constraint conversion not implemented for: dbo.NoticeSyn_AuthoGroup.DF__NoticeSyn__DTS_U__3D0F74CF
-- -- Source table: [dbo].[NoticeSyn_AuthoGroup]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
