-- TODO: constraint conversion not implemented for: dbo.NoticeSyn_UserByGroup.DF__NoticeSyn__DTS_U__54E6FE60
-- -- Source table: [dbo].[NoticeSyn_UserByGroup]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
