-- TODO: constraint conversion not implemented for: dbo.NoticeSyn_Reference.DF__NoticeSyn__Depar__4DBADDE4
-- -- Source table: [dbo].[NoticeSyn_Reference]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
