-- TODO: constraint conversion not implemented for: dbo.Organization_Departments.DF__Organizat__Sende__70F9F880
-- -- Source table: [dbo].[Organization_Departments]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('')
