-- TODO: constraint conversion not implemented for: dbo.Organization_BelongToDepartment.DF_BelongToDepartment_IsDefault
-- -- Source table: [dbo].[Organization_BelongToDepartment]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('1')
