-- TODO: constraint conversion not implemented for: dbo.Organization_Positions.DF_Organization_Positions_Name_VN
-- -- Source table: [dbo].[Organization_Positions]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('')
