-- TODO: constraint conversion not implemented for: dbo.ProposalCommonCode.DF_ProposalCommonCode_SortOrder
-- -- Source table: [dbo].[ProposalCommonCode]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((1))
