-- TODO: constraint conversion not implemented for: dbo.ProposalCommonClass.DF_ProposalCommonClass_UseYn
-- -- Source table: [dbo].[ProposalCommonClass]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (N'N')
