-- TODO: constraint conversion not implemented for: dbo.ProposalCommonCode.DF_ProposalCommonCode_ModDate
-- -- Source table: [dbo].[ProposalCommonCode]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
