-- TODO: constraint conversion not implemented for: dbo.ProposalUserApproval.PK_ProposalUserApproval_1
-- -- Source table: [dbo].[ProposalUserApproval]
-- -- Constraint type: PRIMARY_KEY_CONSTRAINT
--
