-- TODO: constraint conversion not implemented for: dbo.ScheduleCalendarSetup.DF_ScheduleCalendarSetup_RegDate
-- -- Source table: [dbo].[ScheduleCalendarSetup]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('1900-01-01')
