-- TODO: constraint conversion not implemented for: dbo.ScheduleCalendarSetup.DF_ScheduleCalendarSetup_RegUserNo
-- -- Source table: [dbo].[ScheduleCalendarSetup]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
