-- TODO: constraint conversion not implemented for: dbo.ScheduleCalendarsOutlook.DF_ScheduleCalendarsOutlook_OutlookEntryID
-- -- Source table: [dbo].[ScheduleCalendarsOutlook]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('')
