-- TODO: constraint conversion not implemented for: dbo.ScheduleDdays.DF_ScheduleDdays_RepeatEndDate
-- -- Source table: [dbo].[ScheduleDdays]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
