-- TODO: constraint conversion not implemented for: dbo.ScheduleDdaysDelete.DF_ScheduleDdaysDelete_IsHoliday
-- -- Source table: [dbo].[ScheduleDdaysDelete]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
