-- TODO: constraint conversion not implemented for: dbo.ScheduleDdaysDelete.DF_ScheduleDdaysDelete_RepeatEndDate
-- -- Source table: [dbo].[ScheduleDdaysDelete]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
