-- TODO: constraint conversion not implemented for: dbo.ScheduleDdaysDelete.DF_ScheduleDdaysDelete_IsLunar
-- -- Source table: [dbo].[ScheduleDdaysDelete]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('0')
