-- TODO: constraint conversion not implemented for: dbo.ScheduleDdaysHistory.DF_ScheduleDdayHistory_HistoryType
-- -- Source table: [dbo].[ScheduleDdaysHistory]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('')
