-- TODO: constraint conversion not implemented for: dbo.ScheduleDdaySharers.DF_ScheduleDdaySharers_PositionNo
-- -- Source table: [dbo].[ScheduleDdaySharers]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
