-- TODO: constraint conversion not implemented for: dbo.ScheduleResourceNotifications.PK_ScheduleResourceNotifications
-- -- Source table: [dbo].[ScheduleResourceNotifications]
-- -- Constraint type: PRIMARY_KEY_CONSTRAINT
--
