-- TODO: constraint conversion not implemented for: dbo.ScheduleResourceReservations.DF_ScheduleResourceReservations_RsvnStatus
-- -- Source table: [dbo].[ScheduleResourceReservations]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('RW')
