-- TODO: constraint conversion not implemented for: dbo.ScheduleResourceReservationsRevision.DF_ScheduleResourceReservationsRevision_ResourceNo
-- -- Source table: [dbo].[ScheduleResourceReservationsRevision]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
