-- TODO: constraint conversion not implemented for: dbo.ScheduleResourceReservations.DF_ScheduleResourceReservations_UserView
-- -- Source table: [dbo].[ScheduleResourceReservations]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
