-- TODO: constraint conversion not implemented for: dbo.ScheduleResources.DF_ScheduleResources_BuyGroupNo
-- -- Source table: [dbo].[ScheduleResources]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
