-- TODO: constraint conversion not implemented for: dbo.ScheduleResourcesRepair.DF_ScheduleResourcesRepair_LastUserNo
-- -- Source table: [dbo].[ScheduleResourcesRepair]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
