-- TODO: constraint conversion not implemented for: dbo.ScheduleResourceSetup.PK_ScheduleResourceSetup
-- -- Source table: [dbo].[ScheduleResourceSetup]
-- -- Constraint type: PRIMARY_KEY_CONSTRAINT
--
