-- TODO: constraint conversion not implemented for: dbo.SourceControl_Company.DF_SourceControl_Company_CreateDate
-- -- Source table: [dbo].[SourceControl_Company]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
