-- TODO: constraint conversion not implemented for: dbo.SourceControl_Company.DF_SourceControl_Company_Disable
-- -- Source table: [dbo].[SourceControl_Company]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((1))
