-- TODO: constraint conversion not implemented for: dbo.SurveyPollEtcComments.DF_SurveyPollEtcComments_EtcComment
-- -- Source table: [dbo].[SurveyPollEtcComments]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ('')
