-- TODO: constraint conversion not implemented for: dbo.TCMCollectMoneyMaster.DF_TCMCollectMoneyMaster_CustomerID
-- -- Source table: [dbo].[TCMCollectMoneyMaster]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
