-- TODO: constraint conversion not implemented for: dbo.WorkingTime_AllowDevices.DF_WorkingTime_AllowDevice_IsUserFull
-- -- Source table: [dbo].[WorkingTime_AllowDevices]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((0))
