-- TODO: constraint conversion not implemented for: dbo.WorkingTime_AllowDevices.DF_WorkingTime_AllowDevices_ModDate
-- -- Source table: [dbo].[WorkingTime_AllowDevices]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- (getdate())
