-- TODO: constraint conversion not implemented for: dbo.WorkingTime_LocationsOutside.DF__WorkingTi__Enabl__655D5D4B
-- -- Source table: [dbo].[WorkingTime_LocationsOutside]
-- -- Constraint type: DEFAULT_CONSTRAINT
-- ((1))
