-- ─── TABLE: DMake_Boards_Fields ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."DMake_Boards_Fields" (
    FieldNo serial NOT NULL,
    BoardNo integer DEFAULT 0,
    ControlNo integer DEFAULT 0,
    Label_KO character varying(100) DEFAULT '',
    Label_EN character varying(100) DEFAULT '',
    Label_JP character varying(100) DEFAULT '',
    Label_CH character varying(100) DEFAULT '',
    Label_VN character varying(100) DEFAULT '',
    FieldUpNo integer DEFAULT 0,
    SortNo integer DEFAULT 999,
    ListNo integer DEFAULT 999,
    ListYN character varying(1) DEFAULT 'N',
    SearchYN character varying(1) DEFAULT 'N',
    FieldName character varying(50) DEFAULT '',
    FieldDataType character varying(50) DEFAULT '',
    FieldType character varying(5) DEFAULT 'T',
    FieldReadOnly character varying(1) DEFAULT 'N',
    FieldRequire character varying(1) DEFAULT 'N',
    Width character varying(10) DEFAULT '',
    Height character varying(10) DEFAULT '',
    ClassNo integer DEFAULT 0,
    PopupYn character varying(1) DEFAULT 'N',
    PopupLink character varying(1000) DEFAULT '',
    ImagePath character varying(500) DEFAULT '',
    Enabled boolean DEFAULT true,
    LabelTextAlign character varying(20) DEFAULT 'text-left',
    LabelBackColor character varying(20) DEFAULT 'lightgray',
    LabelFontWeight character varying(20) DEFAULT 'normal',
    ChartYN character varying(1) DEFAULT 'N'
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
