-- ─── TABLE: DMake_Contents ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."DMake_Contents" (
    ContentNo bigserial NOT NULL,
    BoardNo integer DEFAULT 0,
    Title character varying(200) DEFAULT '',
    TitleEffect integer DEFAULT 0,
    Content text DEFAULT '',
    IsFile boolean DEFAULT false,
    FileCount integer DEFAULT 0,
    ReplyCount integer DEFAULT 0,
    RecommendedCount integer DEFAULT 0,
    ViewedCount integer DEFAULT 0,
    IsDeleted boolean DEFAULT false,
    StartDate character varying(10) DEFAULT '',
    EndDate character varying(10) DEFAULT '',
    IsHead boolean DEFAULT false,
    IsApproval character varying(1) DEFAULT 'D',
    ApprovalUserNo integer DEFAULT 0,
    ApprovalDate timestamp without time zone,
    IsAnomymous boolean DEFAULT false,
    ParentNo integer DEFAULT 0,
    RegUserNo integer DEFAULT 0,
    RegUserName character varying(100) DEFAULT '',
    RegDate timestamp without time zone DEFAULT now(),
    ModUserNo integer DEFAULT 0,
    ModUserName character varying(100) DEFAULT '',
    ModDate timestamp without time zone DEFAULT now(),
    DMakeField01 character varying(100) DEFAULT '',
    DMakeField02 character varying(100) DEFAULT '',
    DMakeField03 character varying(100) DEFAULT '',
    DMakeField04 character varying(100) DEFAULT '',
    DMakeField05 character varying(100) DEFAULT '',
    DMakeField06 character varying(100) DEFAULT '',
    DMakeField07 character varying(100) DEFAULT '',
    DMakeField08 character varying(100) DEFAULT '',
    DMakeField09 character varying(100) DEFAULT '',
    DMakeField10 character varying(100) DEFAULT ''
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
