-- ─── TABLE: EAPPProgress ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."EAPPProgress" (
    ID serial NOT NULL,
    DocumentID integer,
    ManagerID character varying(50),
    Depth integer,
    ArriveState integer,
    ArriveDate timestamp without time zone,
    ManageState integer,
    ManageDate timestamp without time zone,
    AccessType integer,
    AccessKey character varying(50),
    ProgressState integer,
    LineOrder integer,
    RepresentID character varying(50),
    Opinion text,
    DepartID character varying(4),
    PositionID character varying(4),
    GradeID character varying(4),
    IsClose character(1),
    IsDelete character(1),
    NextDrafter character(1),
    DepartName1 character varying(50),
    PositionName1 character varying(50),
    GradeName1 character varying(50),
    DepartName2 character varying(50),
    PositionName2 character varying(50),
    GradeName2 character varying(50),
    DepartName3 character varying(50),
    PositionName3 character varying(50),
    GradeName3 character varying(50),
    DepartName4 character varying(50),
    PositionName4 character varying(50),
    GradeName4 character varying(50)
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
