-- ─── TABLE: ScheduleResourceReservations ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."ScheduleResourceReservations" (
    ReservationNo serial NOT NULL,
    RegUserNo integer NOT NULL,
    RegDate timestamp without time zone NOT NULL,
    ModUserNo integer NOT NULL,
    ModDate timestamp without time zone NOT NULL,
    Title character varying(100) NOT NULL,
    ResourceNo integer NOT NULL,
    Content character varying(500) NOT NULL,
    RepeatType integer NOT NULL,
    RepeatCount integer NOT NULL,
    RepeatMonth integer NOT NULL,
    RepeatWeek integer NOT NULL,
    RepeatDay integer NOT NULL,
    RepeatDOWs integer NOT NULL,
    StartDate date NOT NULL,
    EndDate date NOT NULL,
    StartTime time without time zone NOT NULL,
    EndTime time without time zone NOT NULL,
    IsNotiNote boolean NOT NULL,
    IsNotiMail boolean NOT NULL,
    IsNotiSMS boolean NOT NULL,
    IsNotiPopup boolean NOT NULL,
    NotiTimeType integer NOT NULL,
    RsvnStatus character(2) NOT NULL DEFAULT 'RW',
    ProcessDate timestamp without time zone NOT NULL DEFAULT '1900-01-01',
    ProcessUserNo integer NOT NULL DEFAULT 0,
    Reason character varying(500) NOT NULL DEFAULT '',
    ProcessView boolean NOT NULL DEFAULT false,
    UserView boolean NOT NULL DEFAULT false,
    IsAllDay boolean
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
