-- ─── TABLE: _TCAUser ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."_TCAUser" (
    CompanySeq integer,
    UserSeq integer NOT NULL,
    UserId character varying(100),
    UserType integer NOT NULL,
    UserName character varying(100),
    EmpSeq integer,
    LoginPwd character varying(200),
    Password1 character varying(200),
    Password2 character varying(200),
    Password3 character varying(200),
    CustSeq integer,
    DeptSeq integer,
    UserSecu integer,
    LoginStatus integer,
    LoginDate character varying(8),
    PwdChgDate character varying(8),
    PassHis character varying(2000),
    PwdMailAdder character varying(50),
    LoginFailCnt integer,
    PwdType character(1),
    LoginType integer,
    ManagementType integer,
    LastUserSeq integer,
    LastDateTime timestamp without time zone,
    Dsn character varying(20),
    Remark character varying(100),
    UserlimitDate character varying(8),
    LoginFailFirstTime timestamp without time zone,
    IsLayoutAdmin integer,
    IsGroupWareUser character varying(1),
    SMUserType integer,
    LicenseType integer,
    IsScndAuthCS character(1),
    ScndAuthTypeCS integer,
    IsScndAuthWEB character(1),
    ScndAuthTypeWEB integer,
    IsScndAuthMBL character(1),
    ScndAuthTypeMBL integer
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
