-- ─── TABLE: DMake_Boards ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."DMake_Boards" (
    BoardNo serial NOT NULL,
    Name character varying(100) DEFAULT '',
    Name_EN character varying(100) DEFAULT '',
    Name_JP character varying(100) DEFAULT '',
    Name_CH character varying(100) DEFAULT '',
    Name_VN character varying(100) DEFAULT '',
    Description character varying(1000) DEFAULT '',
    BoardType character varying(1) DEFAULT 'B',
    Enabled boolean DEFAULT true,
    FolderNo integer DEFAULT 0,
    SortNo integer DEFAULT 0,
    IsReply boolean DEFAULT false,
    IsHead boolean DEFAULT false,
    IsRecommend boolean DEFAULT false,
    RecommendedDisplayCount integer DEFAULT 0,
    IsApproval boolean DEFAULT false,
    IsAnomymous boolean DEFAULT false,
    IsNotRightClick boolean DEFAULT false,
    IsAttachFile boolean DEFAULT false,
    IsLog boolean DEFAULT false,
    ChartType character varying(10) DEFAULT 'none',
    ChartColors character varying(200) DEFAULT '',
    RegUserNo integer DEFAULT 0,
    RegDate timestamp without time zone DEFAULT now(),
    ModUserNo integer DEFAULT 0,
    ModDate timestamp without time zone DEFAULT now()
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
