-- ─── TABLE: ScheduleDdays ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public."ScheduleDdays" (
    DdayNo serial NOT NULL,
    RegUserNo integer NOT NULL,
    RegDate timestamp without time zone NOT NULL,
    ModUserNo integer NOT NULL,
    ModDate timestamp without time zone NOT NULL,
    Title character varying(100) NOT NULL,
    Contents text NOT NULL DEFAULT '',
    GroupNo integer NOT NULL,
    DoomDate date NOT NULL,
    IsLunar character(1) NOT NULL DEFAULT '0',
    IsHoliday integer NOT NULL DEFAULT 0,
    IsFiveWeek character(1) NOT NULL DEFAULT '0',
    IsLastDay character(1) NOT NULL DEFAULT '0',
    PeriodYear integer NOT NULL,
    RepeatEndDate date NOT NULL DEFAULT now(),
    RepeatType integer NOT NULL DEFAULT 0,
    RepeatCount integer NOT NULL DEFAULT 0,
    RepeatMonth integer NOT NULL DEFAULT 0,
    RepeatWeek integer NOT NULL DEFAULT 0,
    RepeatDay integer NOT NULL DEFAULT 0,
    RepeatDOWs integer NOT NULL DEFAULT 0,
    IsNotiNote boolean NOT NULL,
    IsNotiMail boolean NOT NULL,
    IsNotiSMS boolean NOT NULL,
    IsNotiPopup boolean NOT NULL,
    NotiTimeType integer NOT NULL,
    DisplayType character(1) NOT NULL DEFAULT 'D',
    IsComplete character(1) NOT NULL DEFAULT 'N',
    CompleteDate date NOT NULL DEFAULT now()
);
-- TODO: Owner mapping skipped. Target role postgres not verified.
