# extract_failing_lines.ps1
$boardReport = Get-Content "E:\pg_converter_ui\reports\Board_Procedure_Validation.md" -Raw
$contactReport = Get-Content "E:\pg_converter_ui\reports\Contact_Procedure_Validation.md" -Raw

$boardFailures = @()
# Parse Board Failures
$boardSection = ($boardReport -split '### 3b. FAIL\r?\n\r?\n')[1]
$boardLines = ($boardSection -split '\r?\n') | Where-Object { $_ -match '^\|' -and $_ -notmatch 'Procedure' -and $_ -notmatch '----' }
foreach ($line in $boardLines) {
    $parts = $line.Split('|') | ForEach-Object { $_.Trim() }
    if ($parts.Count -ge 4) {
        $proc = $parts[1] -replace '`', ''
        $code = $parts[2] -replace '`', ''
        $err = $parts[3]
        
        # Locate the file and find the matching snippet
        $filePath = "E:\pg_converter_ui\reports\board_failing_sql\$proc.sql"
        $lineNo = 0
        $snippet = ""
        $rootCause = ""
        $suggestedFix = ""
        
        if (Test-Path $filePath) {
            $sqlLines = Get-Content $filePath
            
            if ($err -match 'syntax error at or near ";"') {
                $rootCause = "Greedy regex line merging or double semicolon injection"
                $suggestedFix = "Normalize line endings to \n to prevent \r from shielding the semicolon from lookbehinds"
                for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                    if ($sqlLines[$i] -match ';;' -or $sqlLines[$i] -match '\b(?:THEN|ELSE|BEGIN|LOOP);') {
                        $lineNo = $i + 1
                        $snippet = $sqlLines[$i].Trim()
                        break
                    }
                }
            }
            elseif ($err -match 'syntax error at or near "OPEN"') {
                $rootCause = "Unconverted T-SQL Cursor syntax (missing DECLARE cursor)"
                $suggestedFix = "Rewrite T-SQL Cursor to standard PostgreSQL FOR loop or PL/pgSQL cursor syntax"
                for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                    if ($sqlLines[$i] -match '\bOPEN\b') {
                        $lineNo = $i + 1
                        $snippet = $sqlLines[$i].Trim()
                        break
                    }
                }
            }
            elseif ($err -match 'syntax error at or near "UNION"') {
                $rootCause = "Inner ORDER BY clause placed before UNION ALL inside subquery"
                $suggestedFix = "Strip inner ORDER BY clauses from UNION branches as they are redundant"
                for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                    if ($sqlLines[$i] -match '\bUNION\b') {
                        $lineNo = $i + 1
                        $snippet = $sqlLines[$i].Trim()
                        break
                    }
                }
            }
            elseif ($err -match 'syntax error at or near "GENERATED"') {
                $rootCause = "GENERATED BY DEFAULT AS IDENTITY syntax error on temp table"
                $suggestedFix = "Map IDENTITY columns in temp tables to serial type for compatibility"
                for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                    if ($sqlLines[$i] -match 'GENERATED') {
                        $lineNo = $i + 1
                        $snippet = $sqlLines[$i].Trim()
                        break
                    }
                }
            }
            elseif ($err -match 'syntax error at or near "EXEC"') {
                $rootCause = "Proprietary T-SQL XML query / EXEC sp_xml_preparedocument"
                $suggestedFix = "Rewrite to use PostgreSQL native XMLTABLE functions"
                for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                    if ($sqlLines[$i] -match 'EXEC|sp_xml_') {
                        $lineNo = $i + 1
                        $snippet = $sqlLines[$i].Trim()
                        break
                    }
                }
            }
            elseif ($err -match 'syntax error at end of input') {
                $rootCause = "Mismatched BEGIN/END blocks resulting in missing END IF; / END LOOP;"
                $suggestedFix = "Correct nested block indentation and block termination regexes"
                $lineNo = $sqlLines.Count
                $snippet = $sqlLines[-1].Trim()
            }
            
            if ($lineNo -eq 0) {
                # Fallback to search generic tokens
                for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                    if ($sqlLines[$i] -match ';$') {
                        $lineNo = $i + 1
                        $snippet = $sqlLines[$i].Trim()
                        break
                    }
                }
            }
        }
        
        $boardFailures += [PSCustomObject]@{
            Name = $proc
            SqlState = $code
            Error = $err
            Line = $lineNo
            Snippet = $snippet
            RootCause = $rootCause
            SuggestedFix = $suggestedFix
        }
    }
}

# Print summary
Write-Output "Board failures analyzed: $($boardFailures.Count)"
$boardFailures | Format-Table Name, Line, Error -AutoSize
