# extract_failing_lines_full.ps1
$boardReport = Get-Content "E:\pg_converter_ui\reports\Board_Procedure_Validation.md" -Raw
$contactReport = Get-Content "E:\pg_converter_ui\reports\Contact_Procedure_Validation.md" -Raw

function Get-Failures($reportText, $folder, $prefix) {
    $failures = @()
    $section = ($reportText -split '### 3b. FAIL\r?\n\r?\n')[1]
    if (!$section) { return $failures }
    $lines = ($section -split '\r?\n') | Where-Object { $_ -match '^\|' -and $_ -notmatch 'Procedure' -and $_ -notmatch '----' }
    foreach ($line in $lines) {
        $parts = $line.Split('|') | ForEach-Object { $_.Trim() }
        if ($parts.Count -ge 4) {
            $proc = $parts[1] -replace '`', ''
            if (!$proc.StartsWith($prefix)) { continue }
            $code = $parts[2] -replace '`', ''
            $err = $parts[3]
            
            $filePath = "E:\pg_converter_ui\reports\$folder\$proc.sql"
            $lineNo = 0
            $snippet = ""
            $rootCause = "Unknown syntax error"
            $suggestedFix = "Review the line and fix manually"
            
            if (Test-Path $filePath) {
                $sqlLines = Get-Content $filePath
                
                if ($err -match 'syntax error at or near ";"') {
                    $rootCause = "Accidental double semicolon (;;) or trailing semicolon on keywords (e.g. THEN;)"
                    $suggestedFix = "Normalize carriage returns (\r) to UNIX line endings (\n) at the start of ConvertBody, and fix statement boundary check lookbehinds."
                    for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                        if ($sqlLines[$i] -match ';;' -or $sqlLines[$i] -match '\b(?:THEN|ELSE|BEGIN|LOOP);') {
                            $lineNo = $i + 1
                            $snippet = $sqlLines[$i].Trim()
                            break
                        }
                    }
                }
                elseif ($err -match 'syntax error at or near "OPEN"') {
                    $rootCause = "Unconverted T-SQL Cursor syntax (missing DECLARE cursor)"
                    $suggestedFix = "Rewrite T-SQL Cursor to standard PostgreSQL FOR record IN SELECT ... LOOP loop structure."
                    for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                        if ($sqlLines[$i] -match '\bOPEN\b') {
                            $lineNo = $i + 1
                            $snippet = $sqlLines[$i].Trim()
                            break
                        }
                    }
                }
                elseif ($err -match 'syntax error at or near "UNION"') {
                    $rootCause = "Inner ORDER BY clause placed before UNION ALL inside subquery"
                    $suggestedFix = "Strip inner ORDER BY clauses from UNION branches as they are redundant."
                    for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                        if ($sqlLines[$i] -match '\bUNION\b') {
                            $lineNo = $i + 1
                            $snippet = $sqlLines[$i].Trim()
                            break
                        }
                    }
                }
                elseif ($err -match 'syntax error at or near "GENERATED"') {
                    $rootCause = "GENERATED BY DEFAULT AS IDENTITY syntax error on temp table"
                    $suggestedFix = "Map IDENTITY columns in temp tables to serial type for compatibility."
                    for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                        if ($sqlLines[$i] -match 'GENERATED') {
                            $lineNo = $i + 1
                            $snippet = $sqlLines[$i].Trim()
                            break
                        }
                    }
                }
                elseif ($err -match 'syntax error at or near "EXEC"') {
                    $rootCause = "Proprietary T-SQL XML query / EXEC sp_xml_preparedocument"
                    $suggestedFix = "Rewrite to use PostgreSQL native XMLTABLE functions."
                    for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                        if ($sqlLines[$i] -match 'EXEC|sp_xml_') {
                            $lineNo = $i + 1
                            $snippet = $sqlLines[$i].Trim()
                            break
                        }
                    }
                }
                elseif ($err -match 'syntax error at or near "RETURN"') {
                    $rootCause = "Missing semicolon on preceding DML line or invalid RETURN query statement"
                    $suggestedFix = "Add semicolon to preceding line. If returning set of records, use RETURN QUERY."
                    for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                        if ($sqlLines[$i] -match '\bRETURN\b') {
                            $lineNo = $i + 1
                            $snippet = $sqlLines[$i].Trim()
                            break
                        }
                    }
                }
                elseif ($err -match 'historynolist" is not a known variable') {
                    $rootCause = "Parameter parsing failure: parameter with comment block before it was unparsed/ignored"
                    $suggestedFix = "Strip single-line SQL comments (-- ...) from the raw parameter block before splitting and parsing."
                    for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                        if ($sqlLines[$i] -match 'historynolist') {
                            $lineNo = $i + 1
                            $snippet = $sqlLines[$i].Trim()
                            break
                        }
                    }
                }
                elseif ($err -match 'invalid input syntax for type date: "GETDATE"') {
                    $rootCause = "GETDATE function in parameter default incorrectly wrapped in single quotes as 'GETDATE'"
                    $suggestedFix = "Update MapDefault to convert GETDATE/GETDATE() function call to CURRENT_DATE/now() instead of wrapping in quotes."
                    for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                        if ($sqlLines[$i] -match 'GETDATE') {
                            $lineNo = $i + 1
                            $snippet = $sqlLines[$i].Trim()
                            break
                        }
                    }
                }
                elseif ($err -match 'syntax error at end of input') {
                    $rootCause = "Mismatched BEGIN/END blocks resulting in missing END IF; / END LOOP;"
                    $suggestedFix = "Correct nested block indentation and block termination regexes."
                    $lineNo = $sqlLines.Count
                    $snippet = $sqlLines[-1].Trim()
                }
                
                if ($lineNo -eq 0) {
                    for ($i = 0; $i -lt $sqlLines.Count; $i++) {
                        if ($sqlLines[$i] -match ';$') {
                            $lineNo = $i + 1
                            $snippet = $sqlLines[$i].Trim()
                            break
                        }
                    }
                }
            }
            
            $failures += [PSCustomObject]@{
                Name = $proc
                SqlState = $code
                Error = $err
                Line = $lineNo
                Snippet = $snippet
                RootCause = $rootCause
                SuggestedFix = $suggestedFix
            }
        }
    }
    return $failures
}

$boardFails = Get-Failures $boardReport "board_failing_sql" "Board_"
$contactFails = Get-Failures $contactReport "contact_failing_sql" "Contact"

Write-Output "=== BOARD FAILURES ($($boardFails.Count)) ==="
$boardFails | Format-Table Name, Line, Error -AutoSize

Write-Output "`n=== CONTACT FAILURES ($($contactFails.Count)) ==="
$contactFails | Format-Table Name, Line, Error -AutoSize

# Export lists to temporary scratch files for writing the markdown report
$boardFails | ConvertTo-Json -Depth 10 | Out-File -FilePath E:\pg_converter_ui\scratch\board_fails.json -Encoding utf8
$contactFails | ConvertTo-Json -Depth 10 | Out-File -FilePath E:\pg_converter_ui\scratch\contact_fails.json -Encoding utf8
